concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
jobs:
  check:
    if: github.repository == 'checkstyle/checkstyle'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Install groovy
      run: sudo apt install groovy
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup local maven cache
      uses: actions/cache@v4
      with:
        key: checkstyle-maven-cache-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
    - continue-on-error: true
      env:
        MAVEN_OPTS: -Xmx4g
      name: Execute checker framework
      run: groovy ./.ci/checker-framework.groovy checker-${{ matrix.profile }}
    - continue-on-error: true
      if: failure()
      name: Git Diff on fail
      run: git diff && git diff > target/checker-${{ matrix.profile }}.patch
    - continue-on-error: true
      if: failure()
      name: Share patch as artifact to apply on local
      uses: actions/upload-artifact@v4
      with:
        name: checker-${{ matrix.profile }}-patch
        path: target/checker-${{ matrix.profile }}.patch
        retention-days: 7
    strategy:
      fail-fast: false
      matrix:
        profile:
        - nullness-optional-interning
        - methods-resource-fenum
        - lock-tainting
        - index
        - formatter
        - signature-gui-units-init
        - regex-property-key-compiler-message
        - purity-value-returns
name: Checker
on:
  repository_dispatch:
    types: trigger-ga___checker-framework.yml
