concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
jobs:
  error-prone:
    if: github.repository == 'checkstyle/checkstyle'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Install groovy
      run: sudo apt install groovy
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup local maven cache
      uses: actions/cache@v4
      with:
        key: checkstyle-maven-cache-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
    - continue-on-error: true
      name: Execute Error-Prone on compile phase
      run: groovy ./.ci/error-prone-check.groovy compile
    - continue-on-error: true
      if: always()
      name: Do a clean compile
      run: mvn -e --no-transfer-progress clean compile
    - continue-on-error: true
      if: always()
      name: Execute Error-Prone on test-compile phase
      run: groovy ./.ci/error-prone-check.groovy test-compile
name: Error-Prone
on:
  repository_dispatch:
    types: trigger-ga___error-prone.yml
