concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
jobs:
  check_issues:
    if: github.repository == 'checkstyle/checkstyle'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download checkstyle
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: links
      if: github.event_name == 'pull_request'
      name: PR linked issues
      uses: mondeja/pr-linked-issues-action@v2
    - continue-on-error: true
      id: format-linked-issues
      if: github.event_name == 'pull_request'
      name: Format linked issues
      run: "LINKED_ISSUES=${{ steps.links.outputs.issues }}\nLINKED_ISSUES_FORMATTED=/tmp/linked_issues\n\
        CHECKSTYLE_ISSUE_URL=\"https:\\/\\/github.com\\/checkstyle\\/checkstyle\\\
        /issues\\/\"\nif [ -n \"$LINKED_ISSUES\" ]; then\n  # shellcheck disable=SC2001\n\
        \  echo $LINKED_ISSUES | sed -e 's/,/\\n/g' >> $LINKED_ISSUES_FORMATTED\n\
        \  sed -i \"s/^/$CHECKSTYLE_ISSUE_URL/\" $LINKED_ISSUES_FORMATTED\nfi\necho\
        \ \"linked-issues-formatted=$LINKED_ISSUES_FORMATTED\" >> \"$GITHUB_OUTPUT\"\
        \n"
    - continue-on-error: true
      env:
        GITHUB_HEAD_REF: ${{ github.head_ref }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LINKED_ISSUES: ${{ steps.format-linked-issues.outputs.linked-issues-formatted
          }}
        PR_HEAD_REPO_NAME: ${{ github.event.pull_request.head.repo.full_name }}
      name: Check Issues
      run: './.ci/no-old-refs.sh

        '
name: Check no closed issue references
on:
  repository_dispatch:
    types: trigger-ga___no-old-refs.yml
