concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
jobs:
  test:
    continue-on-error: true
    if: github.repository == 'checkstyle/checkstyle'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Install groovy
      run: 'sudo apt update

        sudo apt install groovy

        '
    - continue-on-error: true
      name: Setup local maven cache
      uses: actions/cache@v4
      with:
        key: checkstyle-maven-cache-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Generate pitest-${{ matrix.profile }} report
      run: './.ci/pitest.sh "pitest-${{ matrix.profile }}"

        '
    - continue-on-error: true
      if: failure()
      name: Patch command for pitest-${{ matrix.profile }}
      run: 'printf "\nTo patch suppression list run:\n\n"

        GIT_DIFF=$(git diff)

        printf "patch -p1 << EOF\n%s\nEOF" "$GIT_DIFF"

        exit 1

        '
    - continue-on-error: true
      if: failure() || github.ref == 'refs/heads/master'
      name: Stage results
      run: 'mkdir staging && cp -r target/pit-reports/ staging

        git diff && git diff > target/pitest-${{ matrix.profile }}.patch

        '
    - continue-on-error: true
      if: failure() || github.ref == 'refs/heads/master'
      name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: pitest-${{ matrix.profile }}-coverage-report
        path: 'staging

          target/pitest-${{ matrix.profile }}.patch

          '
        retention-days: 7
    strategy:
      matrix:
        profile:
        - annotation
        - ant
        - api
        - blocks
        - coding-1
        - coding-2
        - coding-require-this-check
        - common
        - common-2
        - design
        - filters
        - header
        - imports
        - indentation
        - javadoc
        - main
        - metrics
        - misc
        - modifier
        - naming
        - packagenamesloader
        - regexp
        - sizes
        - tree-walker
        - utils
        - whitespace
        - xpath
        - java-ast-visitor
name: Pitest
on:
  repository_dispatch:
    types: trigger-ga___pitest.yml
