concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
jobs:
  copy-github-io-to-sourceforge:
    name: Copy github.io to sourceforge.org ${{ inputs.version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout the latest code
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        SF_SSH_KEY: ${{ secrets.SF_SSH_KEY }}
      name: Configure SSH
      run: 'mkdir -p ~/.ssh/

        eval "$(ssh-agent -s)"

        echo "$SF_SSH_KEY" > ~/.ssh/private_sourceforge_key

        chmod 400 ~/.ssh/private_sourceforge_key

        ssh-add ~/.ssh/private_sourceforge_key

        ssh-keyscan -t ed25519 shell.sourceforge.net >> ~/.ssh/known_hosts

        ssh-keyscan -t ed25519 web.sourceforge.net >> ~/.ssh/known_hosts

        '
    - continue-on-error: true
      env:
        SF_USER: ${{ secrets.SF_USER }}
      name: Run Shell Script
      run: './.ci/release-copy-github-io-to-sourceforge.sh ${{ inputs.version }}

        '
name: 'R: Copy github.io to sourceforge.org'
on:
  repository_dispatch:
    types: trigger-ga___release-copy-github-io-to-sourceforge.yml
run-name: 'R: Copy github.io to sourceforge.org ${{ inputs.version }}'
