concurrency:
  cancel-in-progress: true
  group: Caller-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
jobs:
  copy-github-io-to-sourceforge:
    needs: update-github-io
    secrets: inherit
    uses: ./.github/workflows/release-copy-github-io-to-sourceforge.yml
    with:
      version: ${{ inputs.version }}
  maven-perform:
    needs: maven-prepare
    permissions:
      contents: read
    secrets: inherit
    uses: ./.github/workflows/release-maven-perform.yml
    with:
      version: ${{ inputs.version }}
  maven-prepare:
    needs: update-xdoc-with-releasenotes
    permissions:
      contents: write
    uses: ./.github/workflows/release-maven-prepare.yml
    with:
      version: ${{ inputs.version }}
  new-milestone-and-issues-in-other-repos:
    needs: update-github-page
    permissions:
      contents: write
      issues: write
    secrets: inherit
    uses: ./.github/workflows/release-new-milestone-and-issues-in-other-repos.yml
    with:
      version: ${{ inputs.version }}
  update-github-io:
    needs: maven-perform
    secrets: inherit
    uses: ./.github/workflows/release-update-github-io.yml
    with:
      version: ${{ inputs.version }}
  update-github-page:
    needs: maven-perform
    permissions:
      contents: write
    secrets: inherit
    uses: ./.github/workflows/release-update-github-page.yml
    with:
      version: ${{ inputs.version }}
  update-xdoc-with-releasenotes:
    permissions:
      contents: write
    uses: ./.github/workflows/release-update-xdoc-with-releasenotes.yml
    with:
      version: ${{ inputs.version }}
  upload-all-jar:
    needs: update-github-page
    permissions:
      contents: write
    secrets: inherit
    uses: ./.github/workflows/release-upload-all-jar.yml
    with:
      version: ${{ inputs.version }}
name: 'R: Release'
on:
  repository_dispatch:
    types: trigger-ga___release.yml
run-name: 'R: Release ${{ inputs.version }}'
