concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} -${{ github.event.pull_request.number || github.ref
    }}-update-github-io
jobs:
  update-github-io:
    name: Update GitHub.io ${{ inputs.version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout the latest code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        repository: ${{ github.repository_owner }}/checkstyle
    - continue-on-error: true
      name: Setup local maven cache
      uses: actions/cache@v4
      with:
        key: checkstyle-maven-cache-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
    - continue-on-error: true
      name: Run Shell Script
      run: './.ci/generate-website.sh ${{ inputs.version }}

        '
    - continue-on-error: true
      name: Checkout checkstyle.github.io repo
      uses: actions/checkout@v4
      with:
        path: .ci-temp/checkstyle.github.io/
        repository: ${{ github.repository_owner }}/checkstyle.github.io
        token: ${{ secrets.PAT }}
    - continue-on-error: true
      name: Commit and Push to checkstyle.github.io repo
      run: './.ci/release-update-github-io.sh ${{ inputs.version }}

        '
name: 'R: Update GitHub.io'
on:
  repository_dispatch:
    types: trigger-ga___release-update-github-io.yml
run-name: 'R: Update GitHub.io ${{ inputs.version }}'
