concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
jobs:
  check_issues:
    if: github.repository == 'checkstyle/checkstyle'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download checkstyle
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup local maven cache
      uses: actions/cache@v4
      with:
        key: checkstyle-maven-cache-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
    - continue-on-error: true
      name: Check links
      run: ./.ci/run-link-check-plugin.sh
name: Check no broken links
on:
  repository_dispatch:
    types: trigger-ga___run-link-check.yml
