concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  set-milestone:
    if: github.repository == 'checkstyle/checkstyle'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout the latest code
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Set milestone on issue
      run: './.ci/set-milestone-on-referenced-issue.sh ''${{ toJSON(github.event.commits)
        }}''

        '
name: Milestone issue closed by PR
on:
  repository_dispatch:
    types: trigger-ga___set-milestone-on-referenced-issue.yml
permissions:
  issues: write
  pull-requests: write
