concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.event.issue.number || github.ref }}
env:
  AWS_BUCKET_NAME: checkstyle-diff-reports
  AWS_REGION: us-east-2
jobs:
  generate_site:
    needs: parse_pr_info
    outputs:
      message: ${{ steps.out.outputs.message}}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository from origin
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        USER_LOGIN: ${{ github.event.issue.user.login }}
      name: Download checkstyle for PR
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: .ci-temp/checkstyle
        ref: ${{needs.parse_pr_info.outputs.branch}}
        repository: ${{ env.USER_LOGIN }}/checkstyle
    - continue-on-error: true
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-region: ${{ env.AWS_REGION }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - continue-on-error: true
      name: Setup local maven cache
      uses: actions/cache@v4
      with:
        key: checkstyle-maven-cache-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
    - continue-on-error: true
      name: Generate site
      run: 'bash

        cd .ci-temp/checkstyle

        mvn -e --no-transfer-progress clean site -Pno-validations -Dmaven.javadoc.skip=false

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPOSITORY_OWNER: ${{ github.repository_owner }}
      name: Copy site to AWS S3 Bucket
      run: 'bash

        TIME=$(date +%Y%H%M%S)

        FOLDER="${{needs.parse_pr_info.outputs.commit_sha}}_$TIME"

        SITE=".ci-temp/checkstyle/target/site"

        LINK="https://${{env.AWS_BUCKET_NAME}}.s3.${{env.AWS_REGION}}.amazonaws.com"

        aws s3 cp "$SITE" "s3://${{env.AWS_BUCKET_NAME}}/$FOLDER/" --recursive

        echo "$LINK/$FOLDER/index.html" > .ci-temp/message

        ./.ci/generate-extra-site-links.sh ${{ github.event.issue.number }} "$LINK/$FOLDER"

        '
    - continue-on-error: true
      id: out
      name: Set output
      run: './.ci/append-to-github-output.sh "message" "$(cat .ci-temp/message)"

        '
  parse_pr_info:
    if: github.event.comment.body == 'GitHub, generate web site' || github.event.comment.body
      == 'GitHub, generate website' || github.event.comment.body == 'GitHub, generate
      site'
    outputs:
      branch: ${{ steps.branch.outputs.ref }}
      commit_sha: ${{ steps.branch.outputs.commit_sha }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: React with rocket on run
      uses: shanegenschaw/pull-request-comment-trigger@v2.1.0
      with:
        reaction: rocket
        trigger: ','
    - continue-on-error: true
      if: 'true'
      run: echo We print it here for this action to work
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Getting PR description
      run: "mkdir -p .ci-temp\ncurl --fail-with-body -X GET \"${{github.event.issue.pull_request.url}}\"\
        \ \\\n    -H \"Accept: application/vnd.github+json\" \\\n    -H \"Authorization:\
        \ token $GITHUB_TOKEN\" \\\n    -o .ci-temp/info.json\n\njq .head.ref .ci-temp/info.json\
        \ > .ci-temp/branch\njq .head.sha .ci-temp/info.json > .ci-temp/commit_sha\n"
    - continue-on-error: true
      id: branch
      name: Set branch
      run: 'echo "ref=$(xargs < .ci-temp/branch)" >> "$GITHUB_OUTPUT"

        echo "commit_sha=$(xargs < .ci-temp/commit_sha | cut -c 1-7)" >> "$GITHUB_OUTPUT"

        '
  send_message:
    if: failure() || success()
    needs:
    - generate_site
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        MSG: ${{needs.generate_site.outputs.message}}
      name: Get message
      run: "mkdir -p .ci-temp\nif [ -z  \"$MSG\" ]; then\n  JOBS_LINK=\"https://github.com/checkstyle/checkstyle/actions/runs/${{github.run_id}}\"\
        \n  API_LINK=\"https://api.github.com/repos/checkstyle/checkstyle/actions/runs/\"\
        \n  API_LINK=\"${API_LINK}${{github.run_id}}/jobs\"\n  echo \"API_LINK=${API_LINK}\"\
        \n\n  curl --fail-with-body -X GET \"${API_LINK}\" \\\n    -H \"Accept: application/vnd.github+json\"\
        \ \\\n    -H \"Authorization: token $GITHUB_TOKEN\" \\\n    -o .ci-temp/info.json\n\
        \n  jq '.jobs' .ci-temp/info.json > \".ci-temp/jobs\"\n  jq '.[] | select(.conclusion\
        \ == \"failure\") | .name' .ci-temp/jobs > .ci-temp/job_name\n  jq '.[] |\
        \ select(.conclusion == \"failure\") | .steps' .ci-temp/jobs > .ci-temp/steps\n\
        \  jq '.[] | select(.conclusion == \"failure\") | .name' .ci-temp/steps >\
        \ .ci-temp/step_name\n  echo \"Site generation job failed on phase $(cat .ci-temp/job_name),\"\
        \ > .ci-temp/message\n  echo \"step $(cat .ci-temp/step_name).<br>Link: $JOBS_LINK\"\
        \ >> .ci-temp/message\nelse\n  echo \"$MSG\" > .ci-temp/message\nfi\n"
    - continue-on-error: true
      id: out
      name: Set message
      run: './.ci/append-to-github-output.sh "message" "$(cat .ci-temp/message)"

        '
    - continue-on-error: true
      name: Comment PR
      uses: checkstyle/contribution/comment-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message: ${{steps.out.outputs.message}}
name: Site
on:
  repository_dispatch:
    types: trigger-ga___site.yml
permissions:
  contents: read
  pull-requests: write
